name: Lint

on:
  push:
    branches:    
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/lint.yml'
      - './BuildTools/.swift-format'
      - '**/*.swift'

jobs:
  Lint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: make swift-lint